### ISSUE TITLE
[REQ] Support key for returning information

### ISSUE THREAD

**Issue by crashzk** [1Mack/CS2-VipManager#4]
It would be interesting to support keys to return information, so we can customize the messages that the plugin sends, for example.

- **`{NAME}`** - Players nickname
- **`{GROUP}`** - Players VIP group **_(I believe that for this suggestion we need some improvements to the plugin https://github.com/1Mack/CS2-VipManager/issues/3)_**
- **`{TIMELEFT}`** - Time remaining for VIP to expire
- **`{EXIRES}`** - Date the VIP will expire

**Comment by 1Mack** [comment]
Good idea. The only point here is that i don't know a way to do it globally, so i would have to change it per message

**Comment by crashzk** [comment]
> Good idea. The only point here is that i don't know a way to do it globally, so i would have to change it per message

Can it help you? https://github.com/partiusfabaa/cs2-advertisement

This uses this resource that you mentioned, TAGS and such.

**Comment by 1Mack** [comment]
It's already done. I'm just fixing things that broke in the last version of css. After that i'll release a new version
